# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'OcssBusiness' do

  pod 'AFNetworking', '~> 3.2.1'
  pod 'MJRefresh', '~> 3.2.0'
  pod 'SDWebImage', '~> 5.0.6'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'YYModel', '~> 1.0.4'
  pod 'TTTAttributedLabel', '~> 2.0.0'
  pod 'WHC_AutoLayoutKit', '~> 2.8.4'
  pod 'MGJRouter', '~> 0.10.0'
  pod 'IQKeyboardManager', '~> 6.4.0'
  pod 'ReactiveObjC', '~> 3.1.1'
  pod 'ZFJFormKit', '~> 1.0.0'

  target 'OcssBusinessTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OcssBusinessUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
